services:
  goboxd:
    build: .
    privileged: true
    ports:
      - "8080:8080"
    restart: unless-stopped
    sysctls: []
    security_opt:
      - no-new-privileges:false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
